version: '3.8'

networks:
  net:
    driver: overlay
    attachable: true

configs:
  prometheus_rules:
    file: ./prometheus.yml

services:
  prometheus:
    image: prom/prometheus:v2.2.0-rc.0
    ports:
      - 9090:9090
    networks:
      - net
    configs:
      - source: prometheus_rules
        target: /etc/prometheus/prometheus.yml
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          memory: 2048M
        reservations:
          memory: 128M

  agent-exporter-0:
    image: python-teste
    ports:
      - 9100:8000
    networks:
      - net
    deploy:
      mode: global
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

  agent-exporter-1:
    image: python-teste
    ports:
      - 9101:8000
    networks:
      - net
    deploy:
      mode: global
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

  agent-exporter-2:
    image: python-teste
    ports:
      - 9102:8000
    networks:
      - net
    deploy:
      mode: global
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

  agent-exporter-3:
    image: python-teste
    ports:
      - 9103:8000
    networks:
      - net
    deploy:
      mode: global
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

  agent-exporter-4:
    image: python-teste
    ports:
      - 9104:8000
    networks:
      - net
    deploy:
      mode: global
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
  