global:
  # Intervalo de raspagem de métricas. O padrão é a cada 60s
  scrape_interval:  10s
  # Intervalo para avaliação de regras. O padrão é a cada 60s
  evaluation_interval: 10s
  # scrape_timeout é definido como o padrão global (10s).

#alerting:
  #alertmanagers:
  #- static_configs:
    #- targets:
    # - alertmanager:9093

#rule_files:
   # - "first_rules.yml"
   # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
  # metrics_path defaults to '/metrics'
  #    scheme defaults to 'http'.
    static_configs:
    - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
    - targets: ['agent-exporter-0:8000','agent-exporter-1:8000','agent-exporter-2:8000','agent-exporter-3:8000','agent-exporter-4:8000' ]

